.TH NAMAZU "1" "May 2014" "namazu of Namazu 2.0.21" "Namazu Project"
.SH NAME
bnamazu \- a web browser wrapper for namazu command
.SH SYNOPSIS
.B bnamazu
[-n] [-b browser] [\fInamazu's options\fR] \fI<query> \fR[\fIindex\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
bnamazu, a seach program with a web browser
.TP
\fB\-n\fR
open a new window when you browse with netscape.
.TP
\-b\fR \fIbrowser-comman\fR
set your faborite browser for browsing. The default is lynx.
.TP
.SH "REPORTING BUGS"
Report bugs to <http://www.namazu.org/trac-namazu/trac.cgi>
or <bug-namazu@namazu.org>.
.SH COPYRIGHT
Copyright \(co 1997-1999 Satoru Takabayashi All rights reserved.
.br
Copyright \(co 2000-2014 Namazu Project All rights reserved.
.br
This is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
