.TH NAMAZU "1" "May 2014" "namazu of Namazu 2.0.21" "Namazu Project"
.SH NAME
mailutime \- set specified file's mtime from RFC822 Date field.
.SH SYNOPSIS
.B mailutime <files> ...
.SH DESCRIPTION
.\" Add any additional description here
.PP
mailutime is a tool to modify specifiled files timestamp(mtime)
from RFC822(email/news) message's Date format or MHonArc messages.
mknmz builds NMZ.field.date from the file's mtime.
.SH "REPORTING BUGS"
Report bugs to <http://www.namazu.org/trac-namazu/trac.cgi>
or <bug-namazu@namazu.org>.
.SH COPYRIGHT
Copyright \(co 1997-1999 Satoru Takabayashi All rights reserved.
.br
Copyright \(co 2000-2014 Namazu Project All rights reserved.
.br
This is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
