#! /bin/sh
#
# Check whether idx1 and idx3 indices are same.
#
# idx1: simply indexed.
# idx3: indexed with --checkpoint and $ON_MEMORY_MAX is 0.
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG

cd idx1
targets=`find . -type f -name 'NMZ.*' -print | \
              egrep -v "NMZ\.(log|r|slog|status|err)$"`  # Exclude them.
cd ..

for target in $targets; do
    diff "idx1/$target" "idx3/$target"
    test "$?" != "0" && exit 1  # error if not success
done
exit 0
