#! /bin/sh
#
# Test for simple indexing.
#
# select-data returns data/en or data/ja depending on environment.
LOG=`pwd`/test-log
TARGET=`$srcdir/select-data`

# help
echo '  *** mknmz --help' >>$LOG
../scripts/mknmz --help >> $LOG

# show-config
echo '  *** mknmz -C' >>$LOG
../scripts/mknmz -C >> $LOG

echo '  *** starting ' $0 >>$LOG

if test ! -d idx1; then
    mkdir idx1
else
    rm -f idx1/NMZ.*
fi

origfilenum=`ls $TARGET|wc -l`

# Simple indexing.
../scripts/mknmz  -O idx1 $TARGET >> $LOG
test "$?" != "0" && exit 1  # error if not success

filenum=`ls $TARGET|wc -l`
test $filenum != $origfilenum && exit 1  # error if not equal

exit 0
