#! /bin/sh
#
# Test for DOCUMENT_NAME variable
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG
. ${srcdir}/commonfuncs
pwd=`pwd`
tmprc="$pwd/../src/.namazurc"
echo "Index $pwd/idx19" > $tmprc
duprcs

# To make messages English
unset LANG;        export LANG
LANGUAGE=C;        export LANGUAGE
LC_ALL=C;          export LC_ALL
unset LC_MESSAGES; export LC_MESSAGES
unset LC_CTYPE;    export LC_CTYPE

SCRIPT_NAME='namazu.cgi'
QUERY_STRING=''
export SCRIPT_NAME QUERY_STRING 

cd ../src
RESULT=`./namazu.cgi | grep $SCRIPT_NAME | wc -l`
if [ $RESULT -ne 2 ]
then
	exit 1
fi

QUERY_STRING='query=namazu'
export QUERY_STRING 

RESULT=`./namazu.cgi | grep $SCRIPT_NAME | wc -l`
if [ $RESULT -ne 3 ]
then
	exit 1
fi

exit 0
