#! /bin/sh
#
# Test for namazu. Two indices are searched at once.
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG

docnum=`perl -lne 'print $1 if /^files (\d+)/' "idx1/NMZ.status"`
docnum=`expr $docnum + $docnum`

# Check simple searching.
cd ../src
./namazu namazu ../tests/idx1 ../tests/idx2 >> $LOG
test "$?" != "0" && exit 1  # error if not success

# Check the number of retrieved documents.
cd ../src
hitnum=`./namazu -c namazu ../tests/idx1 ../tests/idx2`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$docnum" != "$hitnum" && exit 1  # error if not matched

exit 0
