#! /bin/sh
#
# Test for namazu.  Searching an index created with --decode-base64 option.
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG

perl -e 'use MIME::Base64 ();' 2> /dev/null
if [ $? != "0" ]; then
     echo "Skipping because perl module not exist." >> $LOG
     echo "SKIP:" $0 >&2
     exit 77
fi

# 1st parts is "Content-Type: text/plain;" and contain 'baz'.
# 2nd parts is "Content-Type: aplication/x-gzip;" and gziped file contain 'foo'.
# 3rd parts is "Content-Type: aplication/x-gzip;" and gziped file contain 'bar'.

docnum=`perl -lne 'print $1 if /^files (\d+)/' idx22/NMZ.status`

hitnum=`../src/namazu -c foo idx22`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$docnum" != "$hitnum" && exit 1  # error if not matched

hitnum=`../src/namazu -c bar idx22`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$docnum" != "$hitnum" && exit 1  # error if not matched

hitnum=`../src/namazu -c baz idx22`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$docnum" != "$hitnum" && exit 1  # error if not matched

docnum=`perl -lne 'print $1 if /^files (\d+)/' idx23/NMZ.status`

hitnum=`../src/namazu -c foo idx23`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$hitnum" != "0" && exit 1  # error if not matched

hitnum=`../src/namazu -c bar idx23`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$hitnum" != "0" && exit 1  # error if matched

hitnum=`../src/namazu -c baz idx23`
echo "docnum:" $docnum, "hitnum:" $hitnum >> $LOG
test "$docnum" != "$hitnum" && exit 1  # error if matched

exit 0
