#! /bin/sh
#
# Test for buffer overflow
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG

# To make messages English
unset LANG;        export LANG
LANGUAGE=C;        export LANGUAGE
LC_ALL=C;          export LC_ALL
unset LC_MESSAGES; export LC_MESSAGES
unset LC_CTYPE;    export LC_CTYPE

../src/namazu nonexistant `perl -e 'print "x"x3000'` | grep "^No document match" > /dev/null || exit 1
