#! /bin/sh
#
# Test for emphasised keyword
#
LOG=`pwd`/test-log
IDX=`pwd`/idx17
echo '  *** starting ' $0 >>$LOG

# To make messages English
unset LANG;        export LANG
LANGUAGE=C;        export LANGUAGE
LC_ALL=C;          export LC_ALL
unset LC_MESSAGES; export LC_MESSAGES
unset LC_CTYPE;    export LC_CTYPE

../src/namazu -h 'emphasise' $IDX | grep "emphasised" > /dev/null || exit 1
